vim.cmd "colorscheme catppuccin"
vim.cmd "highlight! PmenuSel guibg=#8bbd94 guifg=#282828"
vim.cmd "highlight! CmpItemAbbr guifg=#ffffff"
vim.cmd "highlight! FloatBorder guifg=#7D7A99"
vim.cmd "highlight! TelescopeSelection guibg=#3d7b48 guibg=none"
vim.cmd "highlight! TelescopeMatching guifg=#27fca0"
vim.cmd "highlight! lualine_c_normal guibg=#2f333d"
vim.cmd "highlight! lualine_b_normal guibg=#2f333d"
vim.cmd "highlight! WhichKeyFloat guibg=none"
vim.cmd "highlight! WhichKeyBorder guibg=none"
